name: CI

on:
  push:
    branches:
      - main  # You can change this to another branch if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout your repo's code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change this to your desired Node.js version

    - name: Run tests
      run: |
        echo "Running tests..."  # Replace with actual test commands
        npm install
        npm test  # Ensure you have some tests to run in your repo
